### ISSUE TITLE
查看源码过程中发现内存泄漏，也许是笔误

### ISSUE THREAD

**Issue by jizhongqing** [huoyu820125/Micro-Development-Kit#2]
代码位置：
//数据写入缓冲
bool IOBuffer::WriteData( char *data, unsigned int nSize )
{
       // 下面if和else都PrepareBuffer了，这里再PrepareBuffer是多余的，会造成内存泄漏
    unsigned char *ioBuf = 0; // PrepareBuffer( nSize ); 
    uint32 nSendSize = 0;
    //数据加入发送缓冲，交给底层去发送
    while ( true )
    {
        if ( nSize > BUFBLOCK_SIZE )
        {
            ioBuf = PrepareBuffer( BUFBLOCK_SIZE );
            memcpy( ioBuf, &data[nSendSize], BUFBLOCK_SIZE );
            WriteFinished( BUFBLOCK_SIZE );
            nSendSize += BUFBLOCK_SIZE;
            nSize -= BUFBLOCK_SIZE;
        }
        else
        {
            ioBuf = PrepareBuffer( nSize );
            memcpy( ioBuf, &data[nSendSize], nSize );
            WriteFinished( nSize );
            break;
        }
    }

```
return true;
```

}

**Comment by huoyu820125** [comment]
// 下面if和else都PrepareBuffer了，这里再PrepareBuffer是多余的，会造成内存泄漏
unsigned char *ioBuf = 0; // PrepareBuffer( nSize );

注解的意思是，如果再执行PrepareBuffer，就是多余的，会造成泄露，不执行就不会泄露

实际代码是没有执行PrepareBuffer，只赋值了一个0
